const legoColors = [
  {
    fullName: '001 - White',
    id: 1,
    name: 'White',
    qElement: true,
    inStock: true,
    rgb: { red: 255, green: 255, blue: 255 },
    cmyk: { cyan: 0, magenta: 0, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: '0, 0, 0, 0',
  },
  {
    fullName: '005 - Brick Yellow',
    id: 5,
    name: 'Brick Yellow',
    qElement: true,
    inStock: true,
    rgb: { red: 176, green: 160, blue: 111 },
    cmyk: { cyan: 14, magenta: 20, yellow: 50, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 467 C',
  },
  {
    fullName: '018 - Nougat',
    id: 18,
    name: 'Nougat',
    qElement: true,
    inStock: false,
    rgb: { red: 187, green: 128, blue: 90 },
    cmyk: { cyan: 11, magenta: 53, yellow: 68, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 472 C',
  },
  {
    fullName: '021 - Bright Red',
    id: 21,
    name: 'Bright Red',
    qElement: true,
    inStock: true,
    rgb: { red: 180, green: 0, blue: 1 },
    cmyk: { cyan: 0, magenta: 100, yellow: 100, black: 7 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 485 C',
  },
  {
    fullName: '023 - Bright Blue',
    id: 23,
    name: 'Bright Blue',
    qElement: true,
    inStock: true,
    rgb: { red: 31, green: 90, blue: 168 },
    cmyk: { cyan: 100, magenta: 55, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 300 C',
  },
  {
    fullName: '024 - Bright Yellow',
    id: 24,
    name: 'Bright Yellow',
    qElement: true,
    inStock: true,
    rgb: { red: 249, green: 200, blue: 10 },
    cmyk: { cyan: 0, magenta: 19, yellow: 100, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 109 C',
  },
  {
    fullName: '026 - Black',
    id: 26,
    name: 'Black',
    qElement: true,
    inStock: true,
    rgb: { red: 0, green: 0, blue: 0 },
    cmyk: { cyan: 40, magenta: 30, yellow: 30, black: 100 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE BLACK C',
  },
  {
    fullName: '028 - Dark Green',
    id: 28,
    name: 'Dark Green',
    qElement: true,
    inStock: true,
    rgb: { red: 0, green: 133, blue: 42 },
    cmyk: { cyan: 100, magenta: 0, yellow: 100, black: 15 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 347 C',
  },
  {
    fullName: '037 - Bright Green',
    id: 37,
    name: 'Bright Green',
    qElement: true,
    inStock: false,
    rgb: { red: 88, green: 171, blue: 65 },
    cmyk: { cyan: 84, magenta: 0, yellow: 100, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 362 C',
  },
  {
    fullName: '038 - Dark Orange',
    id: 38,
    name: 'Dark Orange',
    qElement: true,
    inStock: false,
    rgb: { red: 153, green: 81, blue: 48 },
    cmyk: { cyan: 22, magenta: 73, yellow: 100, black: 20 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 1605 C',
  },
  {
    fullName: '102 - Medium Blue',
    id: 102,
    name: 'Medium Blue',
    qElement: true,
    inStock: true,
    rgb: { red: 114, green: 150, blue: 200 },
    cmyk: { cyan: 68, magenta: 24, yellow: 5, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 542 C',
  },
  {
    fullName: '106 - Bright Orange',
    id: 106,
    name: 'Bright Orange',
    qElement: true,
    inStock: true,
    rgb: { red: 213, green: 121, blue: 34 },
    cmyk: { cyan: 0, magenta: 63, yellow: 100, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 1505 C',
  },
  {
    fullName: '107 - Bright Bluish Green',
    id: 107,
    name: 'Bright Bluish Green',
    qElement: true,
    inStock: false,
    rgb: { red: 0, green: 152, blue: 148 },
    cmyk: { cyan: 100, magenta: 0, yellow: 48, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 3282 C',
  },
  {
    fullName: '119 - Bright Yellowish Green',
    id: 119,
    name: 'Bright Yellowish Green',
    qElement: true,
    inStock: true,
    rgb: { red: 165, green: 202, blue: 24 },
    cmyk: { cyan: 45, magenta: 5, yellow: 100, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 390 C',
  },
  {
    fullName: '124 - Bright Red Violet',
    id: 124,
    name: 'Bright Red Violet',
    qElement: true,
    inStock: true,
    rgb: { red: 144, green: 31, blue: 118 },
    cmyk: { cyan: 28, magenta: 100, yellow: 12, black: 2 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 675 C',
  },
  {
    fullName: '135 - Sand Blue',
    id: 135,
    name: 'Sand Blue',
    qElement: true,
    inStock: true,
    rgb: { red: 112, green: 129, blue: 154 },
    cmyk: { cyan: 60, magenta: 37, yellow: 25, black: 11 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 5415 C',
  },
  {
    fullName: '138 - Sand Yellow',
    id: 138,
    name: 'Sand Yellow',
    qElement: true,
    inStock: false,
    rgb: { red: 137, green: 126, blue: 98 },
    cmyk: { cyan: 34, magenta: 40, yellow: 62, black: 19 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 7503 C',
  },
  {
    fullName: '140 - Earth Blue',
    id: 140,
    name: 'Earth Blue',
    qElement: true,
    inStock: true,
    rgb: { red: 25, green: 50, blue: 90 },
    cmyk: { cyan: 100, magenta: 72, yellow: 30, black: 38 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 539 C',
  },
  {
    fullName: '141 - Earth Green',
    id: 141,
    name: 'Earth Green',
    qElement: true,
    inStock: true,
    rgb: { red: 0, green: 69, blue: 25 },
    cmyk: { cyan: 100, magenta: 58, yellow: 100, black: 33 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 3435 C',
  },
  {
    fullName: '151 - Sand Green',
    id: 151,
    name: 'Sand Green',
    qElement: true,
    inStock: true,
    rgb: { red: 111, green: 142, blue: 124 },
    cmyk: { cyan: 56, magenta: 22, yellow: 54, black: 12 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 556 C',
  },
  {
    fullName: '154 - Dark Red',
    id: 154,
    name: 'Dark Red',
    qElement: true,
    inStock: true,
    rgb: { red: 115, green: 0, blue: 18 },
    cmyk: { cyan: 28, magenta: 100, yellow: 93, black: 38 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 1807 C',
  },
  {
    fullName: '191 - Flame Yellowish Orange',
    id: 191,
    name: 'Flame Yellowish Orange',
    qElement: true,
    inStock: true,
    rgb: { red: 252, green: 172, blue: 0 },
    cmyk: { cyan: 0, magenta: 37, yellow: 100, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 137 C',
  },
  {
    fullName: '192 - Dark Reddish Brown',
    id: 192,
    name: 'Dark Reddish Brown',
    qElement: true,
    inStock: true,
    rgb: { red: 94, green: 49, blue: 8 },
    cmyk: { cyan: 32, magenta: 80, yellow: 95, black: 50 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 175 C',
  },
  {
    fullName: '194 - Medium Stone Gray',
    id: 194,
    name: 'Medium Stone Gray',
    qElement: true,
    inStock: true,
    rgb: { red: 150, green: 150, blue: 150 },
    cmyk: { cyan: 40, magenta: 32, yellow: 34, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 428 C',
  },
  {
    fullName: '199 - Dark Stone Gray',
    id: 199,
    name: 'Dark Stone Gray',
    qElement: true,
    inStock: true,
    rgb: { red: 100, green: 100, blue: 100 },
    cmyk: { cyan: 67, magenta: 57, yellow: 59, black: 10 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE COOLGRAY 10C',
  },
  {
    fullName: '212 - Light Royal Blue',
    id: 212,
    name: 'Light Royal Blue',
    qElement: true,
    inStock: false,
    rgb: { red: 158, green: 195, blue: 247 },
    cmyk: { cyan: 49, magenta: 10, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 278 C',
  },
  {
    fullName: '221 - Bright Purple',
    id: 221,
    name: 'Bright Purple',
    qElement: true,
    inStock: true,
    rgb: { red: 212, green: 53, blue: 156 },
    cmyk: { cyan: 5, magenta: 80, yellow: 2, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 218 C',
  },
  {
    fullName: '222 - Light Purple',
    id: 222,
    name: 'Light Purple',
    qElement: true,
    inStock: true,
    rgb: { red: 254, green: 156, blue: 203 },
    cmyk: { cyan: 5, magenta: 48, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 244 C',
  },
  {
    fullName: '226 - Cool Yellow',
    id: 226,
    name: 'Cool Yellow',
    qElement: true,
    inStock: false,
    rgb: { red: 255, green: 236, blue: 108 },
    cmyk: { cyan: 0, magenta: 0, yellow: 65, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 113 C',
  },
  {
    fullName: '268 - Medium Lilac',
    id: 268,
    name: 'Medium Lilac',
    qElement: true,
    inStock: true,
    rgb: { red: 67, green: 26, blue: 144 },
    cmyk: { cyan: 88, magenta: 100, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 268 C',
  },
  {
    fullName: '283 - Light Nougat',
    id: 283,
    name: 'Light Nougat',
    qElement: true,
    inStock: false,
    rgb: { red: 225, green: 190, blue: 161 },
    cmyk: { cyan: 0, magenta: 27, yellow: 37, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 488 C',
  },
  {
    fullName: '297 - Warm Gold',
    id: 297,
    name: 'Warm Gold',
    qElement: true,
    inStock: false,
    rgb: { red: 175, green: 133, blue: 34 },
    cmyk: { cyan: 6, magenta: 40, yellow: 95, black: 25 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 125 C',
  },
  {
    fullName: '308 - Dark Brown',
    id: 308,
    name: 'Dark Brown',
    qElement: true,
    inStock: false,
    rgb: { red: 53, green: 33, blue: 0 },
    cmyk: { cyan: 49, magenta: 80, yellow: 82, black: 72 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 4625 C',
  },
  {
    fullName: '312 - Medium Nougat',
    id: 312,
    name: 'Medium Nougat',
    qElement: true,
    inStock: true,
    rgb: { red: 170, green: 125, blue: 84 },
    cmyk: { cyan: 22, magenta: 54, yellow: 77, black: 15 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 729 C',
  },
  {
    fullName: '321 - Dark Azur',
    id: 321,
    name: 'Dark Azur',
    qElement: true,
    inStock: false,
    rgb: { red: 70, green: 155, blue: 195 },
    cmyk: { cyan: 89, magenta: 12, yellow: 4, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 299 C',
  },
  {
    fullName: '322 - Medium Azur',
    id: 322,
    name: 'Medium Azur',
    qElement: true,
    inStock: false,
    rgb: { red: 104, green: 195, blue: 226 },
    cmyk: { cyan: 71, magenta: 0, yellow: 17, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 311 C',
  },
  {
    fullName: '323 - Aqua',
    id: 323,
    name: 'Aqua',
    qElement: true,
    inStock: false,
    rgb: { red: 211, green: 242, blue: 234 },
    cmyk: { cyan: 25, magenta: 0, yellow: 21, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 317 C',
  },
  {
    fullName: '324 - Medium Lavendar',
    id: 324,
    name: 'Medium Lavendar',
    qElement: true,
    inStock: false,
    rgb: { red: 160, green: 110, blue: 185 },
    cmyk: { cyan: 40, magenta: 60, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 528 C',
  },
  {
    fullName: '325 - Lavendar',
    id: 325,
    name: 'Lavendar',
    qElement: true,
    inStock: true,
    rgb: { red: 205, green: 164, blue: 222 },
    cmyk: { cyan: 25, magenta: 35, yellow: 0, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 264 C',
  },
  {
    fullName: '326 - Spring Yellowish Green',
    id: 326,
    name: 'Spring Yellowish Green',
    qElement: true,
    inStock: false,
    rgb: { red: 226, green: 249, blue: 154 },
    cmyk: { cyan: 22, magenta: 0, yellow: 52, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 373 C',
  },
  {
    fullName: '330 - Olive Green',
    id: 330,
    name: 'Olive Green',
    qElement: true,
    inStock: true,
    rgb: { red: 139, green: 132, blue: 79 },
    cmyk: { cyan: 50, magenta: 38, yellow: 77, black: 11 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 5825 C',
  },
  {
    fullName: '353 - Vibrant Coral',
    id: 353,
    name: 'Vibrant Coral',
    qElement: true,
    inStock: false,
    rgb: { red: 240, green: 109, blue: 120 },
    cmyk: { cyan: 0, magenta: 70, yellow: 45, black: 0 },
    colorCorrection: {
      toCMYK: { h: 0, s: 0, l: 0 },
      toRGB: { h: 0, s: 0, l: 0 },
    },
    pantone: 'PANTONE 178 C',
  },
];

export default legoColors;
